services:
  postgres:
    image: postgres:15-alpine
    container_name: khmermarket-postgres
    environment:
      POSTGRES_DB: khmermarket_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d khmermarket_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - khmermarket-network
    restart: unless-stopped

  user-service:
    image: pisithly/backend-user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/khmermarket_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - khmermarket-network
    restart: unless-stopped

  frontend:
    image: pisithly/fronted-frontend:latest
    container_name: khmermarket-frontend
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://167.172.92.243:8080
      NUXT_PUBLIC_API_BASE_URL: http://167.172.92.243:8080
      APP_NAME: KhmerMarket
      NUXT_PUBLIC_APP_NAME: KhmerMarket
      NODE_ENV: production
    depends_on:
      - user-service
    networks:
      - khmermarket-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  khmermarket-network:
    driver: bridge
